name: Build Quotex Signal Bot Executable

on:
  workflow_dispatch:

jobs:
  build_executable:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install yfinance pandas numpy requests pyinstaller

      - name: Clean PyInstaller cache and build executable
        run: |
          pyinstaller --clean --log-level=DEBUG --onefile quotex_signal_generator.py

      - name: List dist folder content
        run: dir dist

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: quotex_signal_generator_exe
          path: dist/quotex_signal_generator.exe
