name: Build Quotex Signal Bot Executable

on:
  workflow_dispatch:  # Manual trigger in GitHub UI

jobs:
  build_executable:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --clean quotex_signal_generator.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: quotex_signal_generator_exe
          path: dist/quotex_signal_generator.exe
