name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile quotex_signal_generator.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: quotex-signal-bot
        path: dist/quotex_signal_generator.exe
