name: Build Quotex Signal Generator EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.6.0

    - name: Setup Python 3.11
      uses: actions/setup-python@v4.9.1
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v3.4.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile quotex_signal_generator.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: quotex-signal-bot-exe
        path: dist/quotex_signal_generator.exe
