name: Build Quotex Signal Bot Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy requests
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile quotex_signal_generator.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: quotex_signal_generator_exe
        path: dist/quotex_signal_generator.exe
